### ISSUE TITLE
Venetian dates

### ISSUE THREAD

**Issue by liladude** [swiss-art-research-net/bso-date-parser#1]
Hi!
more a question than a issue: I have several examples from the Venetian archive where there are two issue: 

- everything before 1797 is m.v. (more veneto, year starts on March 1st, i.e. February 25 1651 m.v. is actually 1652 in Gregorian calendar  
- standard months are 7bre, 8bre, 9bre and Xbre (unless in latin),  genaro or zenaro would also appear. Do you need a list?
Best regards,
Elisa

**Comment by fkraeutli** [comment]
Calendar conversions are tricky and are not currently handled by the parser. For this we would probably need another library (do you know any) which can convert dates between calendars.

The additional months could be added here: https://github.com/swiss-art-research-net/bso-date-parser/blob/main/src/sariDateParser/lib/constants.py. You could create a new group for your required language (Latin or Italian) for consistency. 

7bre, 8bre, 9bre and Xbre would be parsed using the French rule. It's not really relevant which language is used to parse it as the language will not be used later on. The order of languages and terms in there is however relevant, as they will be checked after each other. You can see this in the list of Roman numerals. VIII is checked for first and I last. If we would check for I first it would parse any Roman date that has a I in it as January.

**Comment by liladude** [comment]
thanks! i will look better in the code!
